#include "images.h"

const ext_img_desc_t images[33] = {
    { "wifi", &img_wifi },
    { "bluetooth", &img_bluetooth },
    { "battery", &img_battery },
    { "clock", &img_clock },
    { "calendar", &img_calendar },
    { "setting", &img_setting },
    { "message", &img_message },
    { "call", &img_call },
    { "note", &img_note },
    { "file", &img_file },
    { "caculator", &img_caculator },
    { "picture", &img_picture },
    { "temp", &img_temp },
    { "weather", &img_weather },
    { "sound", &img_sound },
    { "brightness", &img_brightness },
    { "audio", &img_audio },
    { "trash", &img_trash },
    { "location", &img_location },
    { "humidity", &img_humidity },
    { "sunny", &img_sunny },
    { "wind", &img_wind },
    { "cloud", &img_cloud },
    { "lightning", &img_lightning },
    { "rain", &img_rain },
    { "stormy", &img_stormy },
    { "pressure", &img_pressure },
    { "windy", &img_windy },
    { "visibility", &img_visibility },
    { "temp2", &img_temp2 },
    { "arrowup", &img_arrowup },
    { "Icon_min", &img_icon_min },
    { "night", &img_night },
};
